[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ✅ 新增：开启 LittleFS 本地文件系统分区
board_build.filesystem = littlefs

lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/Adafruit AS7341 @ ^1.4.1
	adafruit/Adafruit SHT31 Library @ ^2.2.2
	claws/BH1750 @ ^1.3.0
	bodmer/TFT_eSPI @ ^2.5.31
	lvgl/lvgl @ ^8.3.9
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	adafruit/RTClib @ ^2.1.1 ; ✅ 新增：DS3231 时钟驱动库

build_flags = 
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_MISO=12
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=-1
	-D TFT_BL=21
	-D LOAD_GLCD=1
	-D SPI_FREQUENCY=27000000
	-D LV_CONF_SKIP=1
	-D LV_COLOR_DEPTH=16
	-D LV_TICK_CUSTOM=1
	; ✅ 新增：开启大中小字体支持
	-D LV_FONT_MONTSERRAT_12=1
	-D LV_FONT_MONTSERRAT_16=1
	-D LV_FONT_MONTSERRAT_18=1
	-D LV_FONT_MONTSERRAT_20=1
	-D LV_FONT_MONTSERRAT_28=1